# Default parameters for simple network model

network:
  N: 3                # size of the network
  delay: 1.5          # (ms) global delay for all neurons in the group
  weight: 2.0        # (nA) EPSC size
  theta: 10.0         # (mV) firing threshold
  tau: 20.0           # (ms) membrane time constant
  tau_syn: 1.0        # (ms) synapse time constant
  tau_refrac: 5.0     # (ms) refractory period
  v_reset: 0.0        # (mV) reset potential
  R: 1.5              # (MÎ©) membrane resistance
  poisson_rate: 200.0 # (Hz) input firing rate
experiment:
  duration: 1000       # (ms) simulation duration
  timestep: 0.01       # (ms) solver time step
  base_filename: 'results/simple_network_default'
  plot_limits: [0, 1000]
  seed: 456943569
  n_record: 1          # number of neurons to record membrane potential from
